type IAuth = 'manager' | 'master'
type richmenuType = 'defaultRM' | 'memberRM'
type chatSource = 'user' | 'manager' | 'system'
type chatContentType = 'image' | 'text' | 'video' | 'call' | 'slideshow' | 'file' | 'audio'
type preferenceType = 'serviceArea' | 'serviceType'
